version: '3.1'

services:

  redmine:
    image: redmine
    container_name: redmine_web
    restart: always
    ports:
      - ${HOST_PORT}:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: ${DB_PASSWORD}
      REDMINE_SECRET_KEY_BASE: ${SECRET_KEY_BASE}

  db:
      container_name: postgres
      image: postgres:alpine
      environment: 
        - POSTGRES_USER=redmine
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=redmine
      # ports: 
      #   - "54320:5432"
      volumes: 
        - db_data:/var/lib/postgresql/data
      restart: always

volumes: 
  db_data: